# Generated by Django 5.2.3 on 2025-06-20 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0003_investigationcase_pdf_last_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('vigilante', 'Vigilante de Seguridad'), ('front_gate', 'Control de Front Gate'), ('otro', 'Otro')], default='vigilante', max_length=20)),
                ('date', models.DateField(help_text='Fecha a la que corresponde el informe')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='daily_reports/pdfs/')),
                ('notes', models.TextField(blank=True, help_text='Notas u observaciones adicionales')),
                ('related_case', models.ForeignKey(blank=True, help_text='Relaciona este informe con un caso de investigación si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.investigationcase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
