# Generated by Django 5.2.3 on 2025-06-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='pdf_text',
            field=models.TextField(blank=True, help_text='Texto extraído del PDF para búsqueda'),
        ),
    ]
