# Generated by Django 5.2.3 on 2025-07-10 13:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0002_dailyreport_pdf_text'),
        ('investigations', '0004_historicalinvestigationcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDailyReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('vigilante', 'Vigilante de Seguridad'), ('front_gate', 'Control de Front Gate'), ('otro', 'Otro')], default='vigilante', max_length=20)),
                ('date', models.DateField(help_text='Fecha a la que corresponde el informe')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False)),
                ('pdf_file', models.TextField(max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notas u observaciones adicionales')),
                ('pdf_text', models.TextField(blank=True, help_text='Texto extraído del PDF para búsqueda')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, db_constraint=False, help_text='Relaciona este informe con un caso de investigación si aplica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investigations.investigationcase')),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical daily report',
                'verbose_name_plural': 'historical daily reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
