# Generated by Django 5.2.3 on 2025-07-18 14:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Número de presupuesto')),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documento', models.FileField(upload_to='presupuestos/')),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado')], default='pendiente_aprobacion', max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='budgetpilot.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='budgetpilot.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='AdjuntoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='presupuestos/adjuntos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='budgetpilot.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cif', models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetpilot.categoriaproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetpilot.proveedor'),
        ),
        migrations.CreateModel(
            name='HistoricalPresupuesto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Número de presupuesto')),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documento', models.TextField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado')], default='pendiente_aprobacion', max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('actualizado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgetpilot.proveedor')),
            ],
            options={
                'verbose_name': 'historical presupuesto',
                'verbose_name_plural': 'historical presupuestos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
