# Generated by Django 5.2.3 on 2025-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationcase',
            name='conclusiones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
