# Generated by Django 5.2.3 on 2025-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_investigationcase_conclusiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationcase',
            name='pdf_last_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
