# Generated by Django 5.2.3 on 2025-07-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrakaKeyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo o posición')),
                ('departamento', models.CharField(choices=[('Accounting', 'Accounting'), ('Activities', 'Activities'), ('Dirección', 'Dirección'), ('Emergency', 'Emergency'), ('Engineering', 'Engineering'), ('Eulen', 'Eulen'), ('F&B', 'F&B'), ('Front Office', 'Front Office'), ('Golf', 'Golf'), ('Grounds', 'Grounds'), ('Human Resources', 'Human Resources'), ('Housekeeping', 'Housekeeping'), ('IT', 'IT'), ('MOD', 'MOD'), ('Safety & Security', 'Safety & Security'), ('Sales & Marketing', 'Sales & Marketing')], max_length=30, verbose_name='Departamento')),
                ('sistema', models.CharField(choices=[('PMI Tunnel', 'PMI Tunnel'), ('pmimckeytra2 GARITA', 'pmimckeytra2 GARITA'), ('pmimckeytra3 GROUND', 'pmimckeytra3 GROUND')], max_length=30, verbose_name='Sistema')),
                ('tipo_llave', models.CharField(choices=[('Común', 'Común'), ('Individual', 'Individual')], max_length=15, verbose_name='Tipo de llave')),
                ('posicion', models.PositiveIntegerField(verbose_name='Posición de la llave')),
                ('acceso_anterior', models.TextField(blank=True, verbose_name='Acceso anterior')),
                ('solicitud_pdf', models.FileField(blank=True, null=True, upload_to='traka/solicitudes/', verbose_name='Solicitud firmada (PDF)')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Ocupada')),
            ],
            options={
                'ordering': ['sistema', 'posicion'],
                'unique_together': {('sistema', 'posicion')},
            },
        ),
    ]
