# Generated by Django 5.2.3 on 2025-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrakaKeyUserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(max_length=30)),
                ('posicion', models.PositiveIntegerField()),
                ('nombre_anterior', models.CharField(max_length=100)),
                ('nombre_nuevo', models.CharField(max_length=100)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trakakeyuser',
            name='fecha_desasignacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de desasignación'),
        ),
    ]
