# Generated by Django 5.2.3 on 2025-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traka', '0002_trakakeyuserhistory_trakakeyuser_fecha_desasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trakakeyuser',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
    ]
