# Generated by Django 5.2.3 on 2025-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionlineOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(verbose_name='Fecha de solicitud')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre y apellidos')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo o posición')),
                ('eid', models.CharField(max_length=50, verbose_name='EID')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('access_required', models.CharField(choices=[('activities', 'Activities'), ('basico', 'Básico'), ('golf', 'Golf'), ('supervisor_engineering', 'Supervisor Engineering'), ('system_manager', 'System Manager')], max_length=30, verbose_name='Acceso requerido')),
                ('setup_by', models.CharField(max_length=100, verbose_name='Setup by')),
                ('completion_date', models.DateField(verbose_name='Date of completion')),
                ('username_assigned', models.CharField(max_length=100, verbose_name='Username assigned')),
                ('password_assigned', models.CharField(max_length=255, verbose_name='Password assigned (base64)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('manager_signed', models.CharField(max_length=100, verbose_name='Manager que firma la solicitud')),
                ('request_pdf', models.FileField(upload_to='visionline/requests/', verbose_name='Solicitud firmada (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
