# Generated by Django 5.2.3 on 2025-07-10 13:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVisionlineOperator',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('request_date', models.DateField(verbose_name='Fecha de solicitud')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre y apellidos')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo o posición')),
                ('eid', models.CharField(max_length=50, verbose_name='EID')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('access_required', models.CharField(choices=[('activities', 'Activities'), ('basico', 'Básico'), ('golf', 'Golf'), ('supervisor_engineering', 'Supervisor Engineering'), ('system_manager', 'System Manager')], max_length=30, verbose_name='Acceso requerido')),
                ('setup_by', models.CharField(max_length=100, verbose_name='Setup by')),
                ('completion_date', models.DateField(verbose_name='Date of completion')),
                ('username_assigned', models.CharField(max_length=100, verbose_name='Username assigned')),
                ('password_assigned', models.CharField(max_length=255, verbose_name='Password assigned (base64)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('manager_signed', models.CharField(max_length=100, verbose_name='Manager que firma la solicitud')),
                ('request_pdf', models.TextField(max_length=100, verbose_name='Solicitud firmada (PDF)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical visionline operator',
                'verbose_name_plural': 'historical visionline operators',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
