# Generated by Django 5.2.3 on 2025-06-27 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('found_at', models.CharField(max_length=255)),
                ('found_on', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lostfound/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('returned', 'Devuelto'), ('discarded', 'Descartado')], default='pending', max_length=20)),
                ('returned_to', models.CharField(blank=True, max_length=255)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
