# Generated by Django 5.2.3 on 2025-06-27 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='found_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='found_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('returned', 'Devuelto'), ('discarded', 'Descartado'), ('returned_to_associate', 'Entregado al asociado que encontró el objeto')], default='pending', max_length=30),
        ),
    ]
