# Generated by Django 5.2.3 on 2025-06-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_lostfoundnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='found_by',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
