# Generated by Django 5.2.3 on 2025-07-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0004_alter_lostfounditem_found_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de procesar'), ('tramit', 'En tramite'), ('waiting', 'Esperando respuesta del propietario'), ('returned', 'Devuelto al propietario'), ('discarded', 'Descartado'), ('returned_to_associate', 'Entregado al asociado que encontró el objeto'), ('dissapeared', 'Desaparecido')], default='pending', max_length=30),
        ),
    ]
