# Generated by Django 5.2.3 on 2025-07-10 13:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0005_alter_lostfounditem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLostFoundItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('found_at', models.CharField(max_length=255)),
                ('found_on', models.DateTimeField()),
                ('found_by', models.CharField(default='Desconocido', max_length=255)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de procesar'), ('tramit', 'En tramite'), ('waiting', 'Esperando respuesta del propietario'), ('returned', 'Devuelto al propietario'), ('discarded', 'Descartado'), ('returned_to_associate', 'Entregado al asociado que encontró el objeto'), ('dissapeared', 'Desaparecido')], default='pending', max_length=30)),
                ('returned_to', models.CharField(blank=True, max_length=255)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lost found item',
                'verbose_name_plural': 'historical lost found items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
