# Generated by Django 5.2.3 on 2025-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_salida', 'Entradas y Salidas'), ('visita', 'Visitas')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('matricula', models.CharField(blank=True, max_length=30)),
                ('nombre_apellidos', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100)),
                ('donde_se_dirigen', models.CharField(blank=True, max_length=100)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('entrega_tarjeta', models.CharField(blank=True, max_length=30)),
                ('devolucion_tarjeta', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
