# Generated by Django 5.2.3 on 2025-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_accesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
