# Generated by Django 5.2.3 on 2025-08-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_accesos', '0002_alter_registroacceso_hora_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacceso',
            name='hora_entrada',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
