# Generated by Django 5.2.3 on 2025-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTraka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(max_length=100)),
                ('localizacion_tarjeta', models.CharField(blank=True, max_length=100)),
                ('fecha_caducidad', models.DateField()),
            ],
        ),
    ]
