# Generated by Django 5.2.3 on 2025-06-20 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0003_investigationcase_pdf_last_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('robo', 'Robo'), ('caida', 'Caída'), ('colision', 'Colisión de Vehículo'), ('golpe', 'Golpe'), ('desmayo', 'Desmayo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('date', models.DateTimeField(help_text='Fecha y hora del incidente')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_report_pdf', models.FileField(upload_to='incident_reports/pdfs/')),
                ('insurance_case_number', models.CharField(blank=True, help_text='Número de caso de la aseguradora', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_investigation', models.ForeignKey(blank=True, help_text='Relaciona este incidente con una investigación si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.investigationcase')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='incident_management.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incident_reports/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incident_management.incident')),
            ],
        ),
    ]
