# Generated by Django 5.2.3 on 2025-06-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='incident_report_pdf',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_report_docx',
            field=models.FileField(blank=True, help_text='Archivo DOCX del Incident Report', null=True, upload_to='incident_reports/docx/'),
        ),
    ]
