# Generated by Django 5.2.3 on 2025-06-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona afectada'),
        ),
    ]
