# Generated by Django 5.2.3 on 2025-07-10 13:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0002_incident_affected_person'),
        ('investigations', '0004_historicalinvestigationcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('affected_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona afectada')),
                ('date', models.DateTimeField(help_text='Fecha y hora del incidente')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_report_docx', models.TextField(blank=True, help_text='Archivo DOCX del Incident Report', max_length=100, null=True)),
                ('insurance_case_number', models.CharField(blank=True, help_text='Número de caso de la aseguradora', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('docx_text', models.TextField(blank=True, help_text='Texto extraído del DOCX para búsqueda')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incident_management.incidenttype')),
                ('related_investigation', models.ForeignKey(blank=True, db_constraint=False, help_text='Relaciona este incidente con una investigación si aplica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investigations.investigationcase')),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical incident',
                'verbose_name_plural': 'historical incidents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
