# Generated by Django 5.2.3 on 2025-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0003_incidentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='docx_text',
            field=models.TextField(blank=True, help_text='Texto extraído del DOCX para búsqueda'),
        ),
    ]
